@startuml
robust "Server" as S
concise "Client" as C

S has Idle,Processing,Sending
C has Waiting,Active,Done

@0
S is Idle
C is Waiting

@10
S is Processing
C is Active

@20
S is Sending
C is Done
@enduml
