@startuml
robust "Server" as S
concise "Client" as C

@0
S is Idle
C is Waiting

@10
S is Processing
C is Active

@25
S is Idle
C is Waiting

@0 <--> @10 : {setup}
@10 <--> @25 : {processing time}
@enduml
